version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./NewToUk/.env
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=newtouk
      - MYSQL_USER=newtouk
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
