version: '3.8'

services:
  db:
    restart: always
    image: mysql:5.7
    container_name: db
    env_file: .env
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    restart: always
    build: .
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  my-datavolume: