version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    env_file:
      - ./NewToUk/.env
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_PASSWORD=P@$$w0rd"
      - "POSTGRES_USER=newtouk"
      - "POSTGRES_DB=newtouk"

volumes:
  postgres_data: