version: '3'
services:
  db:
    restart: always
    image: mysql:5.7
    container_name: my_db
    env_file: ./NewToUk/.env
    ports:
      - "3306:3306"

  web:
    restart: always
    build: .
    env_file: ./NewToUk/.env
    command: ./wait_for_db.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
