# Generated by Django 4.0.5 on 2022-06-11 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='Models id')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('registration_number', models.CharField(max_length=100, verbose_name='Association or organization registration number')),
                ('languages', models.CharField(max_length=1000, verbose_name='Languages spoken')),
                ('documents', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Documents lawyer uploaded')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentSchedules',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='Models id')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('date', models.DateField(verbose_name='Appointment Schedule date')),
                ('time', models.TimeField(verbose_name='Appointment Time')),
                ('isUsed', models.BooleanField(default=False, verbose_name='Used to check if the appointment schedule has been used by another user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='Models id')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('status', models.CharField(max_length=20, verbose_name='Appointment status e.g Rejected, Scheduled')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal_support.appointmentschedules')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
