# Generated by Django 4.0.5 on 2022-07-07 12:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('15b77a50-4440-443c-976e-5a0f68c5dfc3'), primary_key=True, serialize=False, verbose_name='Models id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('15b77a50-4440-443c-976e-5a0f68c5dfc3'), primary_key=True, serialize=False, verbose_name='Models id'),
        ),
    ]
