# Generated by Django 4.0.5 on 2022-06-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='Models id')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('type', models.CharField(max_length=50)),
                ('images', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
