# Generated by Django 4.0.5 on 2022-08-03 02:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_support', '0004_property_description_property_name_alter_image_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='number_of_bathrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Models id'),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Models id'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Models id'),
        ),
    ]
