# Generated by Django 4.0.5 on 2022-08-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_support', '0006_alter_image_image_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_video_url',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
